language: ruby
rvm:
  - 2.1
env:
  - DB=postgres
before_install:
  - sudo gem update --system
script:
  - sudo pip install ansible
  - make deps
  - ansible-playbook -i cm/inventory cm/playbook.yml --tags 'test'
  - RAILS_ENV=test bundle exec rake db:create db:migrate test
services:
  - redis-server
